SEO and Site Setting
joomla-projects/joomla-browser pull request #169
Opened 2018-06-24 13:46 UTC by Samgithub1997

@yvesh I have made the changes as per your suggestion :)
1. Search engine friendly URLs
2. Site offline/online
@puneet0191

2018-06-24 16:26 UTC, yvesh commented on src/JoomlaBrowser.php
> +		if($enable == true){
if ($enable)
{
   // No else needed this way
   return;
}

// .. else code

2018-06-24 16:26 UTC, yvesh commented on src/JoomlaBrowser.php
> +	public function setSiteOffline($enable)
default value true please - ($enable = true)

2018-06-24 16:26 UTC, yvesh commented on src/JoomlaBrowser.php
> +        $this->amOnPage('/administrator/index.php?option=com_config');
code style

2018-06-24 20:45 UTC, Samgithub1997 commented
Thanks for pointing that out @yvesh .
Can you review it and check if it is ready for merge? @puneet0191

2018-06-25 08:15 UTC, puneet0191 requested changes
@Samgithub1997 please do the changes.

2018-06-25 08:15 UTC, puneet0191 commented on src/JoomlaBrowser.php
> +		$this->waitForText('Control Panel', 4, $this->locator->controlPanelLocator);
why change this?

2018-06-25 08:15 UTC, puneet0191 commented on src/JoomlaBrowser.php
> +            	case 'Articles - Archived' :
I think the styling is all wrong here, also please make sure you only work with branch 4.0 on Joomla Browser, your PR should also be on 4.0, don't send PR for develop branch.

2018-07-16 23:07 UTC, closed without merging